### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by GodziBi**
done

### CODE REVIEW

**Review by bahtibek-an — CHANGES_REQUESTED** [review]
After reloading the home page, then doesn't shows restaurants which i create before.

**Comment by bahtibek-an** [comment]
Send me your full name

**Comment by GodziBi** [comment]
> Bosh sahifani qayta yuklagandan so'ng, men ilgari yaratgan restoranlarni ko'rsatmaydi.

it's not my fault. everyone has that problem due to netlify not working well

**Comment by GodziBi** [comment]
> Menga toʻliq ismingizni yuboring

Asilbek Erkinov

**Comment by bahtibek-an** [comment]
It's not netlify problem, you should using useEffect fetch data from firebase or backend.

**Pull request closed without merging**
